# Generated by Django 3.1.2 on 2020-10-20 03:27

import datetime
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modificado em')),
                ('active', models.DateField(default=datetime.datetime(2020, 10, 20, 3, 27, 6, 577175), verbose_name='Ativo')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=100, verbose_name='e-mail')),
                ('graduation', models.CharField(max_length=100, verbose_name='Graduation')),
                ('phone_number', models.IntegerField(max_length=15, verbose_name='Phone Number')),
                ('picture', stdimage.models.StdImageField(upload_to='product', verbose_name='Picture')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
