# Generated by Django 3.1.2 on 2020-10-20 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 19, 39, 35, 272126), verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phone_number',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
    ]
