# Generated by Django 3.1.2 on 2020-10-20 19:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0002_auto_20201020_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 20, 19, 43, 46, 45668, tzinfo=utc), verbose_name='Ativo'),
        ),
    ]
