# Generated by Django 3.1.2 on 2020-10-31 18:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0007_auto_20201030_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 18, 56, 45, 237184, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 18, 56, 45, 237184, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 18, 56, 45, 237184, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 18, 56, 45, 237184, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('active', models.DateTimeField(default=datetime.datetime(2020, 10, 31, 18, 56, 45, 237184, tzinfo=utc), verbose_name='Active')),
                ('subject_name', models.CharField(max_length=80, verbose_name='Subject Name')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='poster.professor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
