# Generated by Django 3.1.2 on 2020-10-31 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0009_auto_20201031_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 20, 3, 6, 546571, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 20, 3, 6, 546571, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 20, 3, 6, 546571, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 20, 3, 6, 546571, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 20, 3, 6, 546571, tzinfo=utc), verbose_name='Active'),
        ),
    ]
