# Generated by Django 3.1.2 on 2020-10-31 20:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0010_auto_20201031_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 20, 34, 39, 471866, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 20, 34, 39, 471866, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 20, 34, 39, 471866, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 20, 34, 39, 471866, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 20, 34, 39, 471866, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='professor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='poster.professor'),
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('active', models.DateTimeField(default=datetime.datetime(2020, 10, 31, 20, 34, 39, 471866, tzinfo=utc), verbose_name='Active')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='poster.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='poster.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuardianStudentBridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('active', models.DateTimeField(default=datetime.datetime(2020, 10, 31, 20, 34, 39, 471866, tzinfo=utc), verbose_name='Active')),
                ('guardian_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='poster.guardian')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='poster.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('active', models.DateTimeField(default=datetime.datetime(2020, 10, 31, 20, 34, 39, 471866, tzinfo=utc), verbose_name='Active')),
                ('test1', models.IntegerField(blank=True, verbose_name='Test 1')),
                ('test2', models.IntegerField(blank=True, verbose_name='Test 2')),
                ('project', models.IntegerField(blank=True, verbose_name='Project')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='poster.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='poster.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
