# Generated by Django 3.1.2 on 2020-10-31 22:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0011_auto_20201031_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='picture',
            field=models.ImageField(default='static/images/professor-default-picture.jpg', upload_to='', verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 22, 26, 51, 670395, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 22, 26, 51, 670395, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 22, 26, 51, 670395, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='guardianstudentbridge',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 22, 26, 51, 670395, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 22, 26, 51, 670395, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 22, 26, 51, 670395, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 22, 26, 51, 670395, tzinfo=utc), verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='active',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 22, 26, 51, 670395, tzinfo=utc), verbose_name='Active'),
        ),
    ]
