# Generated by Django 3.1.2 on 2020-11-01 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0012_auto_20201031_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='active',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='active',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='active',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='guardianstudentbridge',
            name='active',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='active',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='student',
            name='active',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='active',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='active',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Active'),
        ),
    ]
