# Generated by Django 3.1.2 on 2020-12-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0013_auto_20201101_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='project',
            field=models.FloatField(blank=True, verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='test1',
            field=models.FloatField(blank=True, verbose_name='Test 1'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='test2',
            field=models.FloatField(blank=True, verbose_name='Test 2'),
        ),
    ]
