# Generated by Django 3.1.2 on 2020-12-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poster', '0014_auto_20201210_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='project',
            field=models.FloatField(verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='test1',
            field=models.FloatField(verbose_name='Test 1'),
        ),
        migrations.AlterField(
            model_name='grades',
            name='test2',
            field=models.FloatField(verbose_name='Test 2'),
        ),
    ]
